/* 100 public-domain hymn tunes from the Open Hymnal Project, titled with
   the Korean 찬송가 names they are sung under. Not official 새찬송가 plates. */
module.exports = [
  { id: 'amazing-grace', title: '나 같은 죄인 살리신', titleEn: 'Amazing Grace', abc: 'Amazing_Grace-New_Britain.abc' },
  { id: 'holy-holy-holy', title: '거룩 거룩 거룩', titleEn: 'Holy, Holy, Holy', abc: 'Holy_Holy_Holy-Nicaea.abc' },
  { id: 'what-a-friend', title: '죄짐 맡은 우리 구주', titleEn: 'What a Friend We Have in Jesus', abc: 'What_A_Friend_We_Have_In_Jesus-untitled.abc' },
  { id: 'jesus-loves-me', title: '예수 사랑하심은', titleEn: 'Jesus Loves Me', abc: 'Jesus_Loves_Me-untitled.abc' },
  { id: 'silent-night', title: '고요한 밤 거룩한 밤', titleEn: 'Silent Night', abc: 'Silent_Night-Stille_Nacht.abc' },
  { id: 'joy-to-the-world', title: '기쁘다 구주 오셨네', titleEn: 'Joy to the World', abc: 'Joy_To_The_World-Antioch.abc' },
  { id: 'o-come-all-ye-faithful', title: '참 반가운 신도여', titleEn: 'O Come All Ye Faithful', abc: 'O_Come_All_Ye_Faithful-Adeste_Fideles-Portugese_Hymn.abc' },
  { id: 'hark-the-herald', title: '천사 찬송하기를', titleEn: 'Hark the Herald Angels Sing', abc: 'Hark_The_Herald_Angels_Sing-Mendelssohn.abc' },
  { id: 'o-little-town', title: '오 베들레헴 작은 골', titleEn: 'O Little Town of Bethlehem', abc: 'O_Little_Town_Of_Bethlehem-St_Louis.abc' },
  { id: 'midnight-clear', title: '그 맑고 환한 밤중에', titleEn: 'It Came Upon a Midnight Clear', abc: 'It_Came_Upon_A_Midnight_Clear-Carol.abc' },
  { id: 'first-noel', title: '첫 노엘', titleEn: 'The First Noel', abc: 'The_First_Noel-The_First_Noel.abc' },
  { id: 'angels-we-have-heard', title: '천사들의 노래가', titleEn: 'Angels We Have Heard on High', abc: 'Angels_We_Have_Heard_On_High-Gloria.abc' },
  { id: 'away-in-a-manger', title: '그 어린 주 예수', titleEn: 'Away in a Manger', abc: 'Away_In_A_Manger-Mueller.abc' },
  { id: 'o-come-emmanuel', title: '오라 오라 임마누엘', titleEn: 'O Come O Come Emmanuel', abc: 'O_Come_O_Come_Emmanuel-Veni_Emmanuel.abc' },
  { id: 'mighty-fortress', title: '내 주는 강한 성이요', titleEn: 'A Mighty Fortress Is Our God', abc: 'A_Mighty_Fortress_Is_Our_God-Ein_Feste_Burg_Rhythmic.abc' },
  { id: 'rock-of-ages', title: '만세반석 열리니', titleEn: 'Rock of Ages', abc: 'Rock_of_Ages-Toplady.abc' },
  { id: 'nearer-my-god', title: '내 주를 가까이 하게 함은', titleEn: 'Nearer My God to Thee', abc: 'Nearer_My_God_To_Thee-Bethany.abc' },
  { id: 'blessed-assurance', title: '예수를 나의 구주 삼고', titleEn: 'Blessed Assurance', abc: 'Blessed_Assurance-Blessed_Assurance-Assurance.abc' },
  { id: 'it-is-well', title: '내 평생에 가는 길', titleEn: 'It Is Well with My Soul', abc: 'It_Is_Well_With_My_Soul-It_Is_Well-Ville_Du_Havre.abc' },
  { id: 'he-leadeth-me', title: '예수가 거느리시니', titleEn: 'He Leadeth Me', abc: 'He_Leadeth_Me-He_Leadeth_Me.abc' },
  { id: 'all-hail-the-power', title: '주 예수 이름 높이어', titleEn: 'All Hail the Power of Jesus Name', abc: 'All_Hail_The_Power_Of_Jesus_Name-Coronation.abc' },
  { id: 'come-thou-fount', title: '복의 근원 강림하사', titleEn: 'Come Thou Fount of Every Blessing', abc: 'Come_Thou_Fount-Nettleton.abc' },
  { id: 'crown-him', title: '주 예수 면류관', titleEn: 'Crown Him with Many Crowns', abc: 'Crown_Him_With_Many_Crowns-Diademata.abc' },
  { id: 'how-firm-a-foundation', title: '주의 약속하신 말씀 위에', titleEn: 'How Firm a Foundation', abc: 'How_Firm_A_Foundation-Foundation-Protection.abc' },
  { id: 'i-need-thee', title: '시시각각 주 예수여', titleEn: 'I Need Thee Every Hour', abc: 'I_Need_Thee_Every_Hour-I_Need_Thee_Every_Hour.abc' },
  { id: 'pass-me-not', title: '인애하신 구세주여', titleEn: 'Pass Me Not O Gentle Savior', abc: 'Pass_Me_Not_O_Gentle_Savior-Pass_Me_Not_O_Gentle_Savior.abc' },
  { id: 'be-thou-my-vision', title: '내 맘의 주여 소망 되소서', titleEn: 'Be Thou My Vision', abc: 'Be_Thou_My_Vision-Slane.abc' },
  { id: 'my-hope-is-built', title: '반석 위에 서리라', titleEn: 'My Hope Is Built', abc: 'My_Hope_Is_Built-Melita.abc' },
  { id: 'savior-like-a-shepherd', title: '우리들의 목자이신', titleEn: 'Savior Like a Shepherd Lead Us', abc: 'Savior_Like_A_Shepherd_Lead_Us-Bradbury.abc' },
  { id: 'praise-to-the-lord', title: '만유의 주 앞에', titleEn: 'Praise to the Lord the Almighty', abc: 'Praise_To_The_Lord_The_Almighty-Lobe_Den_Herren.abc' },
  { id: 'now-thank-we-all', title: '다 감사드리세', titleEn: 'Now Thank We All Our God', abc: 'Now_Thank_We_All_Our_God-Nun_Danket.abc' },
  { id: 'old-hundredth-praise', title: '만복의 근원 하나님', titleEn: 'Praise God From Whom All Blessings Flow', abc: 'Praise_God_From_Whom_All_Blessings_Flow-Old_100th.abc' },
  { id: 'jesus-shall-reign', title: '예수 그리스도 우리 왕', titleEn: 'Jesus Shall Reign', abc: 'Jesus_Shall_Reign-Duke_Street.abc' },
  { id: 'when-i-survey', title: '놀라운 십자가', titleEn: 'When I Survey the Wondrous Cross', abc: 'When_I_Survey_The_Wondrous_Cross-Hamburg.abc' },
  { id: 'o-sacred-head', title: '오 거룩하신 주님', titleEn: 'O Sacred Head Now Wounded', abc: 'O_Sacred_Head_Now_Wounded-Passion_Chorale-Herzlich_Tut_Mich_Verlangen.abc' },
  { id: 'christ-the-lord-is-risen', title: '예수 부활했으니', titleEn: 'Christ the Lord Is Risen Today', abc: 'Christ_The_Lord_Is_Risen_Today-Llanfair.abc' },
  { id: 'jesus-christ-is-risen', title: '예수 다시 사셨네', titleEn: 'Jesus Christ Is Risen Today', abc: 'Jesus_Christ_Is_Risen_Today-Easter_Hymn.abc' },
  { id: 'christ-arose', title: '무덤에 머물러', titleEn: 'Christ Arose', abc: 'Christ_Arose-Christ_Arose.abc' },
  { id: 'all-glory-laud', title: '호산나 호산나', titleEn: 'All Glory Laud and Honor', abc: 'All_Glory_Laud_And_Honor-Valet_Will_Ich_Dir_Geben-St_Theodulph.abc' },
  { id: 'hosanna-loud', title: '왕 되신 우리 주께', titleEn: 'Hosanna Loud Hosanna', abc: 'Hosanna_Loud_Hosanna-Ellacombe.abc' },
  { id: 'the-churchs-one-foundation', title: '교회의 참된 터는', titleEn: 'The Churchs One Foundation', abc: 'The_Churchs_One_Foundation-Aurelia.abc' },
  { id: 'for-all-the-saints', title: '성도의 믿음 따라', titleEn: 'For All the Saints', abc: 'For_All_The_Saints-Sine_Nomine.abc' },
  { id: 'faith-of-our-fathers', title: '믿음의 조상들이', titleEn: 'Faith of Our Fathers', abc: 'Faith_Of_Our_Fathers-St_Catherine.abc' },
  { id: 'blest-be-the-tie', title: '우리 다시 만날 때까지', titleEn: 'Blest Be the Tie That Binds', abc: 'Blest_Be_The_Tie_That_Binds-Dennis.abc' },
  { id: 'our-god-our-help', title: '영원히 찬양받으실', titleEn: 'Our God Our Help in Ages Past', abc: 'Our_God_Our_Help_In_Ages_Past-St_Anne.abc' },
  { id: 'o-for-a-thousand', title: '만백성 기뻐하여라', titleEn: 'O For a Thousand Tongues', abc: 'O_For_A_Thousand_Tongues-Azmon.abc' },
  { id: 'hyfrydol-alleluia', title: '할렐루야 우리 예수', titleEn: 'Alleluia Sing to Jesus', abc: 'Alleluia_Sing_To_Jesus-Hyfrydol.abc' },
  { id: 'guide-me', title: '나의 갈 길 다가도록', titleEn: 'Guide Me O Thou Great Jehovah', abc: 'Guide_Me_O_Thou_Great_Jehovah-Cwm_Rhondda.abc' },
  { id: 'immortal-invisible', title: '보이지 않는 하나님', titleEn: 'Immortal Invisible God Only Wise', abc: 'Immortal_Invisible_God_Only_Wise-St_Denio.abc' },
  { id: 'all-creatures', title: '온 천하 만물 우러러', titleEn: 'All Creatures of Our God and King', abc: 'All_Creatures_Of_Our_God_And_King-Lasst_Uns_Erfreuen.abc' },
  { id: 'for-the-beauty', title: '아름다운 하늘과', titleEn: 'For the Beauty of the Earth', abc: 'For_The_Beauty_Of_The_Earth-Dix.abc' },
  { id: 'as-with-gladness', title: '동방에서 박사들', titleEn: 'As With Gladness Men of Old', abc: 'As_With_Gladness_Men_Of_Old-Dix.abc' },
  { id: 'beautiful-savior', title: '아름다운 구세주', titleEn: 'Beautiful Savior', abc: 'Beautiful_Savior-Crusaders_Hymn.abc' },
  { id: 'i-know-whom', title: '아 하나님의 은혜로', titleEn: 'I Know Whom I Have Believed', abc: 'I_Know_Whom_I_Have_Believed-I_Know_Whom_I_Have_Believed.abc' },
  { id: 'i-know-that-my-redeemer', title: '내 구주 살아 계셔', titleEn: 'I Know That My Redeemer Lives', abc: 'I_Know_That_My_Redeemer_Lives-Duke_Street.abc' },
  { id: 'my-faith-looks-up', title: '구주를 생각만 해도', titleEn: 'My Faith Looks Up to Thee', abc: 'My_Faith_Looks_Up_To_Thee-Olivet.abc' },
  { id: 'more-love-to-thee', title: '내 구주 예수를 더욱 사랑', titleEn: 'More Love to Thee', abc: 'More_Love_To_Thee-More_Love_To_Thee.abc' },
  { id: 'jesus-is-all-the-world', title: '예수는 나의 힘이요', titleEn: 'Jesus Is All the World to Me', abc: 'Jesus_Is_All_The_World_to_Me-Jesus_Is_All_The_World_to_Me.abc' },
  { id: 'where-he-leads-me', title: '예수 나를 오라 하네', titleEn: 'Where He Leads Me', abc: 'Where_He_Leads_Me-Where_He_Leads_Me.abc' },
  { id: 'take-my-life', title: '내 몸과 마음을', titleEn: 'Take My Life and Let It Be', abc: 'Take_My_Life_And_Let_It_Be-Mozart.abc' },
  { id: 'beneath-the-cross', title: '십자가 그늘 아래', titleEn: 'Beneath the Cross of Jesus', abc: 'Beneath_The_Cross_Of_Jesus-St_Christopher.abc' },
  { id: 'the-old-rugged-cross', title: '갈보리 산 위에', titleEn: 'The Old Rugged Cross', abc: 'The_Old_Rugged_Cross-Old_Rugged_Cross.abc' },
  { id: 'when-the-roll', title: '저 좋은 낙원 가서', titleEn: 'When the Roll Is Called Up Yonder', abc: 'When_the_Roll_is_Called_Up_Yonder-When_the_Roll_is_Called_Up_Yonder.abc' },
  { id: 'to-god-be-the-glory', title: '하나님께 영광', titleEn: 'To God Be the Glory', abc: 'To_God_Be_the_Glory-To_God_Be_the_Glory.abc' },
  { id: 'rescue-the-perishing', title: '구원으로 인도하는', titleEn: 'Rescue the Perishing', abc: 'Rescue_the_Perishing-Rescue_the_Perishing.abc' },
  { id: 'hark-the-voice', title: '주의 음성 외에는', titleEn: 'Hark the Voice of Jesus Calling', abc: 'Hark_The_Voice_Of_Jesus_Calling-Galilean.abc' },
  { id: 'come-ye-disconsolate', title: '고생하는 이 모두', titleEn: 'Come Ye Disconsolate', abc: 'Come_Ye_Disconsolate-Consolator_Webbe.abc' },
  { id: 'be-still-my-soul', title: '내 영혼아 잠잠하라', titleEn: 'Be Still My Soul', abc: 'Be_Still_My_Soul-Finlandia.abc' },
  { id: 'we-gather-together', title: '성도여 다 함께', titleEn: 'We Gather Together', abc: 'We_Gather_Together-Kremser.abc' },
  { id: 'come-thou-long', title: '오랫동안 고대하던', titleEn: 'Come Thou Long Expected Jesus', abc: 'Come_Thou_Long_Expected_Jesus-Jefferson.abc' },
  { id: 'lo-he-comes', title: '다시 오실 주님', titleEn: 'Lo He Comes on Clouds Descending', abc: 'Lo_He_Comes_On_Clouds_Descending-Helmsley.abc' },
  { id: 'let-all-mortal-flesh', title: '모든 육체들아', titleEn: 'Let All Mortal Flesh Keep Silence', abc: 'Let_All_Mortal_Flesh_Keep_Silence-Picardy.abc' },
  { id: 'what-child-is-this', title: '저 들 밖에 한밤중에', titleEn: 'What Child Is This', abc: 'What_Child_Is_This-Greensleeves.abc' },
  { id: 'angels-from-the-realms', title: '천사 화답하여서', titleEn: 'Angels From the Realms of Glory', abc: 'Angels_From_The_Realms_Of_Glory-Regent_Square.abc' },
  { id: 'god-rest-ye-merry', title: '기쁜 소식을 전하는', titleEn: 'God Rest Ye Merry Gentlemen', abc: 'God_Rest_Ye_Merry_Gentlemen-God_Rest_Ye_Merry_Gentlemen.abc' },
  { id: 'lo-how-a-rose', title: '장미꽃 같은 우리 주', titleEn: 'Lo How a Rose Eer Blooming', abc: 'Lo_How_A_Rose_Eer_Blooming-Es_Ist_Ein_Ros_Entsprungen.abc' },
  { id: 'in-the-bleak-midwinter', title: '한겨울 바람 속에', titleEn: 'In the Bleak MidWinter', abc: 'In_The_Bleak_MidWinter-Cranham.abc' },
  { id: 'go-to-dark-gethsemane', title: '겟세마네 동산에서', titleEn: 'Go to Dark Gethsemane', abc: 'Go_to_Dark_Gethsemane-Gethsemane-Petra.abc' },
  { id: 'stricken-smitten', title: '상하고 찢긴 주님', titleEn: 'Stricken Smitten and Afflicted', abc: 'Stricken_Smitten_And_Afflicted-O_Mein_Jesu_Ich_Muss_Sterben-Wo_Ist_Jesus_Mein_Verlangen.abc' },
  { id: 'the-strife-is-oer', title: '싸움은 모두 끝나고', titleEn: 'The Strife Is Oer the Battle Done', abc: 'The_Strife_Is_Oer_The_Battle_Done-Victory-Palestrina.abc' },
  { id: 'holy-god-we-praise', title: '거룩하신 하나님', titleEn: 'Holy God We Praise Thy Name', abc: 'Holy_God_We_Praise_Thy_Name-Te_Deum-Hursley.abc' },
  { id: 'breathe-on-me', title: '성령이여 강림하사', titleEn: 'Breathe on Me Breath of God', abc: 'Breathe_On_Me_Breath_Of_God-Aylesbury-Wirksworth.abc' },
  { id: 'come-holy-spirit', title: '성령의 봄바람 불어오니', titleEn: 'Come Holy Spirit Lord Our God', abc: 'Come_Holy_Spirit_Lord_Our_God-Komm_Heiliger_Geist_Herre_Gott.abc' },
  { id: 'o-holy-spirit-enter', title: '성령이여 오소서', titleEn: 'O Holy Spirit Enter In', abc: 'O_Holy_Spirit_Enter_In-Wie_Schon_Leuchtet.abc' },
  { id: 'i-am-jesus-little-lamb', title: '나는 예수 어린양', titleEn: 'I Am Jesus Little Lamb', abc: 'I_Am_Jesus_Little_Lamb-Weil_Ich_Jesu_Schaflein_Bin.abc' },
  { id: 'the-lords-my-shepherd', title: '여호와는 나의 목자시니', titleEn: 'The Lords My Shepherd', abc: 'The_Lords_My_Shepherd-Marosa-Brother_James_Air.abc' },
  { id: 'under-his-wings', title: '주의 날개 밑', titleEn: 'Under His Wings', abc: 'Under_His_Wings-Under_His_Wings.abc' },
  { id: 'god-will-take-care', title: '하나님이 돌보실 것', titleEn: 'God Will Take Care of You', abc: 'God_Will_Take_Care_Of_You-Martin.abc' },
  { id: 'no-not-one', title: '세상에 없는 친구', titleEn: 'No Not One', abc: 'No_Not_One-No_Not_One.abc' },
  { id: 'hallelujah-what-a-savior', title: '할렐루야 우리 구주', titleEn: 'Hallelujah What a Savior', abc: 'Hallelujah_What_a_Savior-Hallelujah_What_a_Savior.abc' },
  { id: 'my-saviors-love', title: '주 달려 죽은 십자가', titleEn: 'My Saviors Love', abc: 'My_Saviors_Love-My_Saviors_Love-I_Stand_Amazed_in_the_Presence.abc' },
  { id: 'the-love-of-god', title: '그 크신 하나님의 사랑', titleEn: 'The Love of God', abc: 'The_Love_Of_God-The_Love_Of_God.abc' },
  { id: 'o-the-deep-deep-love', title: '한없는 주님의 사랑', titleEn: 'O the Deep Deep Love of Jesus', abc: 'O_The_Deep_Deep_Love_Of_Jesus-Ebenezer-Ton_Y_Botel.abc' },
  { id: 'all-praise-to-thee', title: '이 밤의 고요함 속에', titleEn: 'All Praise to Thee My God This Night', abc: 'All_Praise_To_Thee_My_God_This_Night-Tallis_Canon.abc' },
  { id: 'awake-my-soul', title: '내 영혼아 깨어나라', titleEn: 'Awake My Soul and with the Sun', abc: 'Awake_My_Soul_And_With_The_Sun-Old_100th.abc' },
  { id: 'joyful-joyful', title: '기뻐하며 경배하세', titleEn: 'Joyful Joyful We Adore Thee', abc: 'Joyful_Joyful_We_Adore_Thee-Ode_To_Joy.abc' },
  { id: 'praise-my-soul', title: '내 영혼아 주를 찬양하라', titleEn: 'Praise My Soul the King of Heaven', abc: 'Praise_My_Soul_The_King_Of_Heaven-Praise_My_Soul-Lauda_Anima.abc' },
  { id: 'glorious-things', title: '시온의 영광이 빛나는 아침', titleEn: 'Glorious Things of Thee Are Spoken', abc: 'Glorious_Things_of_Thee_Are_Spoken-Austria_Haydn-Austrian_Hymn.abc' },
  { id: 'take-up-thy-cross', title: '십자가를 지고', titleEn: 'Take Up Thy Cross the Savior Said', abc: 'Take_Up_Thy_Cross_The_Savior_Said-Nun_Lasst_Uns_Den_Leib_Begraben.abc' },
  { id: 'lamp-of-our-feet', title: '주의 말씀 받고서', titleEn: 'Lamp of Our Feet', abc: 'Lamp_of_Our_Feet-St_Agnes.abc' }
];
